### ISSUE TITLE
System freeze after the Windows logo during reboot after using this tool

### ISSUE THREAD

**Issue by FFreestyleRR** [hardentools/hardentools#123]
I think the issue was related to the LSA protection (Windows 10 22H2).
I had to restore an image since no other methods helped to resolve the issue (Recovery Environment, Safe Mode, System Restore, Last Known Good Configuration, etc.). So Macrium Reflect came to the rescue. I think I will stick to Hard_Configurator or SysHardener for now.
Pls check and resolve the issue in the further versions if possible, so other users won't experience this problem.

Thanks!

**Comment by obsti8383** [comment]
@FFreestyleRR  Why do you think the issue was related to LSA protection? Have you tried without using the (optional) LSA protection setting? Do the other tools you mention also enable LSA protection and are working?

**Comment by FFreestyleRR** [comment]
Hi,

No, I didn't test without the LSA protection yet. This was my first test of the tool, but the other settings sound harmless in comparison to the LSA and some of them were grayed-out already before using this tool (already covered by me). Maybe will be doing so during the weekend because I will not have the time to restore an image during the work days, and I am a little scary to use it again without preparation. :) Or maybe It was the ASR Rules (but I don't have WD enabled anyway). I am using Kaspersky Free and Comodo Firewall combo (with no incompatibility issue). I don't know, maybe HardenTools interfered with some of them. Will doing more tests when I have some free time and will report back.

As for the LSA protection, I didn't use H_C or Syshardener for a while, but they seem to cover the LSA protection (or at least have some LSA protection, even if not the same).

https://malwaretips.com/threads/hard_configurator-windows-hardening-configurator.66416/post-1002429

Best regards!

**Comment by FFreestyleRR** [comment]
Hi,

I was not able to test the tool again due to limited time the last few days. Will try to do so as soon as possible.
But it seems that I am not the only one with the issue after using the tool.

Best regards.

**Comment by obsti8383** [comment]
Hi, yes, any hint which harden setting might cause this would be very appreciated. Already checked the bug tickets from some other tools and didn't find any similar reports yet. By the way: Which exact Windows version are you using?
