### ISSUE TITLE
Inaccessible Boot Device – Blue Screen Of Death

### ISSUE THREAD

**Issue by Dashboardcatpiss** [hardentools/hardentools#124]
Hello there,

yesterday I tried out the hardentools on default settings (with that I mean the simple “harden” button with no advanced adjustments) which worked fine without issues but then when I restarted my computer I got the infamous BSOD with the error code “Inaccessible Boot Device”. 
I am not able to boot into windows any more to restore this mess, and sadly I am not able to use windows safe mode either. Most of the cmd troubleshooting things online didn't work (sfc, dism, chkdsk etc etc.) and it doesn't let me delete any new updates, neither does it let me restore my computer with the option “keeping my files” and as stupid as I am: I don't have any kind of Backups.

Is there anything I can do? Is there any way I can restore the “hardening” through the cmd console? Help is very much appreciated because a computer, which I obviously need, with a BSOD isn't all too useful…

**Comment by obsti8383** [comment]
@Dashboardcatpiss That doesn't sound very good. Restoration of the hardening is only possible from the running windows system with the command line version of hardentools. Only thing you could try is to manually undo hardenings from a rescue system (which needs quite a bit of research and work).
Question: Because this doesn't really sound like a typical hardening issue: Were there some other changes during that Windows session, e.g. installation of Windows updates?

Can you still access your data from a rescue USB drive / live system and backup your data? If yes, I would propose to backup your data and then try a repair installation.

**Comment by Dashboardcatpiss** [comment]
So for whatever reason it doesn't let me boot from the USB Stick, even though I sepparatly put Windows on it...how lovely. Either I am making a stupid mistake which I am not realising or I really did destroy my whole Computer from inside.

**Comment by obsti8383** [comment]
Your BIOS Boot settings are fine?

**Comment by Dashboardcatpiss** [comment]
They should be. I even reset all of my Bios settings to default (not that I changed a lot anyway). But when setting the boot priorities correctly, it doesn't work. A bit astonishing, not going to lie.

**Comment by FFreestyleRR** [comment]
Sorry to interrupt here but seems like exactly my issue in the previous topic. I am glad that I had an Image with Macrium Reflect. Even the keyboard and the mouse stopped working during the reboot when this happened.

**Comment by obsti8383** [comment]
@Dashboardcatpiss which Windows version are you using? Win 10 22H2?

**Comment by Dashboardcatpiss** [comment]
> 

I'm very happy to hear that at least one of us was smart enough to regularly make a recovery image of their system XD

**Comment by Dashboardcatpiss** [comment]
> @Dashboardcatpiss which Windows version are you using? Win 10 22H2?

I think it was 22H2. I always kept my Windows version as recent as possible. So my Windows Version is pretty much the most recent up until last week when I couldn't access my computer any more.

**Comment by jpylypiw** [comment]
Hi there! If this problem still persists I have some ideas how to fix it.
This "Inaccessible Boot Device" error is mostly related to BIOS Settings. For example on Dell Devices you can switch between AHCI and RAID Boot Mode. Whan you change one to another windows throws this "Inaccessible Boot Device" error. If this did not help you can try to disable two settings one after another: The first setting to test is Secure Boot. This might help to disable some security features on startup. The second option is to disable Intel VT-X or AMD Virtualization. This depends on your processor. If you have an Intel Processor this intel setting should be disabled and if you have an AMD Processor, the AMD setting should be disabled. This might help to disable some Virtualization supported boot features in Win 10 and 11.
Hopefully this helps!
