### ISSUE TITLE
Check versions of installed software

### ISSUE THREAD

**Issue by obsti8383** [hardentools/hardentools#75]
Hi All,
Hi @botherder,

what do you think about integrating [https://github.com/obsti8383/UpdateChecker](https://github.com/obsti8383/UpdateChecker) (which i programmed over the last weeks) somehow into hardentools (perhaps using a different UI and also changing other things)?

What's not so good about that is that it requires a connection to a online service to get information about current software versions).

Alternative could be to provide this as a separate tool.

Any kind of feedback greatly appreciated.

Cheers
Florian

P.S.: You can try the compiled alpha release if you like. Otherwise just do a "go build" and execute the binary from within the source directory (it needs the main.html and static/ directory).

**Comment by botherder** [comment]
That's an interesting idea. What do you think is the upside of integrating opposite to keep them separate tools?

**Comment by obsti8383** [comment]
Good question. I see it that way:

Pro integration into Hardentools:
- Disabling obsolete tools like Flash and Java Plugins might be to hard for some users (see #34), so at least warning them about available updates makes sense
- One tool only. I think we won't get the average user to use two different tools

Contra integration into Hardentools:
- Update checking must be executed regularly (in opposite to hardentools which is more "fire and forget")
- It's easier to maintain separate tools
- Hardentools wouldn't need a central infrastructure (server to deliver the current versions)
- Hardentools will stay a tool that is not talking to anyone (might be good to keep it undetected from observers)

**Comment by obsti8383** [comment]
For all interested parties: You can download a new beta version of a separate software doing checks of the installed software on a Windows 10 system here: https://github.com/obsti8383/UpdateChecker/releases/tag/Beta-0.2.3 

Any feedback welcome.

**Comment by botherder** [comment]
Nice one!

**Comment by obsti8383** [comment]
Keeping stuff like this up-to-date requires a central service and is hard to maintain. Closing for now as "won't fix"
